radio.setGroup(5555)
basic.forever(function () {
    basic.pause(100)
    music.playMelody("C5 B C5 G C5 B C5 E ", 120)
})
basic.forever(function () {
    basic.pause(100)
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOn)
    basic.pause(100)
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOff)
    basic.pause(100)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
    basic.pause(100)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOff)
})
basic.forever(function () {
    basic.pause(100)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 50)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 50)
})
basic.forever(function () {
    basic.pause(100)
    radio.sendNumber(1)
    basic.pause(500)
    radio.sendNumber(2)
    basic.pause(500)
    radio.sendNumber(3)
    basic.pause(100)
    radio.sendNumber(4)
    basic.pause(1000)
    radio.sendNumber(5)
    basic.pause(1000)
    radio.sendNumber(6)
    basic.pause(100)
    radio.sendNumber(7)
    basic.pause(1000)
    radio.sendNumber(8)
    basic.pause(1000)
    radio.sendNumber(9)
    basic.pause(100)
})
